name: Trigger site rebuild

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps: [
        {
            name: 'Checkout Code',
            uses: actions/checkout@v2
        },
        {
            name: 'Lint Code Base',
            uses: docker://github/super-linter:latest
            env: {
                VALIDATE_ALL_CODEBASE: false
            }
        },
        {
            name: 'Repository dispatch',
            uses: defold/repository-dispatch@1.2.1,
            with: {
                repo: 'defold/defold.github.io',
                token: '${{ secrets.SERVICES_GITHUB_TOKEN }}',
                user: 'services@defold.se',
                action: 'awesome'
            }
        }]
